all:
	g++ -O2 -fmudflap -I/usr/include/g++/4.4/ -o tarning tarning.c -W -Wall -Wextra -lmudflap
	g++ -O2 -fmudflap -I/usr/include/g++/4.4/ -o tarning2 tarning2.c -W -Wall -Wextra -lmudflap
	g++ -O2 -fmudflap -I/usr/include/g++/4.4/ -o tarning3 tarning3.c -W -Wall -Wextra -lmudflap
