NAME = cookie

all:
	g++ -O2 -I/usr/include/g++/4.4/ -o $(NAME) $(NAME).cc -W -Wall -Wextra

runex:
	@./$(NAME) < ex.in

runsmall:
	@./$(NAME) < small.in

runlarge:
	@./$(NAME) < large.in

run:
	@./$(NAME)
